document.addEventListener('DOMContentLoaded', () => {

    // --- Blog Page Functionality ---
    const blogGrid = document.querySelector('.blog-grid');
    const blogModal = document.getElementById('blog-modal');

    if (blogGrid && blogModal) {
        
        const blogPosts = [
            {
                title: 'Why Secure QR Codes Matter',
                img: 'images/blog1.jpg',
                summary: 'Learn about the risks of insecure QR codes, real world attack examples, and how to protect yourself and your users.',
                author: 'OneScan Team',
                date: '2024-06-01',
                content: `<h2>Introduction</h2><p>QR codes are everywhere, but not all are created equal. Insecure QR codes can be tampered with, leading to phishing, malware, or data theft. Attackers can overlay malicious codes on printed materials or compromise digital displays. Always verify the source and use apps like OneScan that guarantee one time, secure usage.</p><blockquote>"A single insecure QR code can compromise an entire workflow. Security must come first."</blockquote><h3>Common QR Code Threats</h3><ul><li><b>Phishing:</b> Fake QR codes can redirect to phishing sites.</li><li><b>Replay Attacks:</b> Reusing a code can expose sensitive info.</li><li><b>Data Leaks:</b> Unsecured codes may leak private data.</li></ul><div class='callout callout-warning'><b>Tip:</b> Always use a trusted QR code app and check the destination before scanning.</div><h3>How OneScan Solves This</h3><p>OneScan's one time codes eliminate these risks by expiring after a single scan. This ensures your data is never reused or exposed to replay attacks.</p><h3>Conclusion</h3><p>Security is not optional. Choose QR solutions that put your privacy and safety first.</p>`
            },
            {
                title: 'The Power of One Time QR Codes',
                img: 'images/blog2.jpg',
                summary: 'Discover how single use QR codes prevent phishing, replay attacks, and data leaks in modern digital workflows.',
                author: 'OneScan Team',
                date: '2024-06-03',
                content: `<h2>Why One Time Codes?</h2><p>One time QR codes are the gold standard for secure sharing. They ensure that even if a code is intercepted, it cannot be reused. This is vital for sharing tickets, credentials, or private links.</p><div class='callout callout-info'><b>Did you know?</b> Over 60% of QR code attacks involve code reuse or replay.</div><h3>Benefits</h3><ul><li>Prevents code reuse and replay attacks</li><li>Ideal for event tickets, secure logins, and confidential info</li><li>Peace of mind for both sender and receiver</li></ul><img src="images/blog2.jpg" alt="One-Time QR" class="blog-inline-img"><h3>How OneScan Makes It Easy</h3><p>OneScan automates this process, making secure sharing effortless for everyone.</p>`
            },
            {
                title: 'Best Practices for QR Code Security',
                img: 'images/blog3.jpg',
                summary: 'Tips for generating, sharing, and scanning QR codes safely at work, at home, and on the go.',
                author: 'OneScan Team',
                date: '2024-06-05',
                content: `<h2>Stay Safe with QR Codes</h2><ol><li>Always use HTTPS links in your QR codes.</li><li>Never scan codes from unknown sources.</li><li>Use apps that support one time or expiring codes.</li><li>Regularly update your QR code apps for the latest security.</li></ol><div class='callout callout-success'><b>Pro Tip:</b> OneScan is designed with these best practices at its core.</div><img src="images/blog3.jpg" alt="Best Practices" class="blog-inline-img">`
            },
            {
                title: 'How Hackers Exploit QR Codes',
                img: 'images/blog4.jpg',
                summary: 'A deep dive into real world QR code attacks, from fake parking meters to malicious restaurant menus.',
                author: 'OneScan Team',
                date: '2024-06-07',
                content: `<p>Hackers have used QR codes to steal credentials, install malware, and trick users into revealing sensitive data. For example, fake QR stickers on parking meters can redirect to phishing sites. Always check for tampering and use trusted apps like OneScan to scan codes.</p>`
            },
            {
                title: 'The Future of QR Code Authentication',
                img: 'images/blog5.jpg',
                author: 'OneScan Team',
                date: '2024-06-09',
                summary: 'Explore how QR codes are revolutionizing secure logins, two factor authentication, and passwordless access.',
                content: `<p>QR codes are now used for secure logins and 2FA. One time codes generated by apps like OneScan can authenticate users without passwords, reducing the risk of credential theft. The future is passwordless, and QR codes are leading the way.</p>`
            },
            {
                title: 'QR Codes and Privacy: What You Need to Know',
                img: 'images/blog6.jpg',
                author: 'OneScan Team',
                date: '2024-06-11',
                summary: 'Understand the privacy implications of QR codes and how to keep your data safe when scanning or sharing.',
                content: `<p>QR codes can encode personal data, so privacy is crucial. Only share codes with trusted parties and avoid embedding sensitive info in plain text. OneScan encrypts your data and ensures it's only accessible once, protecting your privacy.</p>`
            },
            {
                title: 'How OneScan Works: Under the Hood',
                img: 'images/blog7.jpg',
                author: 'OneScan Team',
                date: '2024-06-13',
                summary: 'A technical look at how OneScan generates, secures, and invalidates one time QR codes for maximum safety.',
                content: `<p>OneScan uses backend validation and cryptographic tokens to ensure each QR code is valid for a single scan. After use, the code is instantly invalidated, preventing reuse. This approach combines usability with enterprise grade security.</p>`
            },
            {
                title: 'Common QR Code Myths Debunked',
                img: 'images/blog9.jpg',
                author: 'OneScan Team',
                date: '2024-06-15',
                summary: 'Are QR codes really unsafe? Can anyone read your data? We separate fact from fiction.',
                content: `<ul><li><b>Myth:</b> All QR codes are dangerous. <b>Fact:</b> Only insecure or reused codes pose risks.</li><li><b>Myth:</b> QR codes always reveal your info. <b>Fact:</b> OneScan encrypts and protects your data.</li></ul>`
            },
            {
                title: 'How to Spot a Malicious QR Code',
                img: 'images/blog10.jpg',
                author: 'OneScan Team',
                date: '2024-06-17',
                summary: 'Practical tips for identifying tampered or fake QR codes in public and online.',
                content: `<p>Look for signs of tampering, such as stickers over original codes. Use apps that preview the link before you open. OneScan always shows you the destination before you proceed.</p>`
            },
            {
                title: 'The Evolution of QR Code Technology',
                img: 'images/blog11.jpg',
                author: 'OneScan Team',
                date: '2024-06-19',
                summary: 'From inventory tracking to secure payments, discover how QR codes have evolved over the years.',
                content: `<p>QR codes started in manufacturing but now power payments, authentication, and more. Security has become a top priority, and OneScan is at the forefront of this evolution.</p>`
            },
            {
                title: 'Building Trust with Secure QR Codes',
                img: 'images/blog12.jpg',
                author: 'OneScan Team',
                date: '2024-06-21',
                summary: 'How businesses can use secure QR codes to build customer trust and loyalty.',
                content: `<p>Customers are wary of QR codes due to security concerns. By using OneScan's one time codes, businesses can reassure users and build lasting trust.</p>`
            },
            {
                title: 'QR Codes for Secure Payments',
                img: 'images/blog13.jpg',
                author: 'OneScan Team',
                date: '2024-06-23',
                summary: 'How one time QR codes are making mobile payments safer and more reliable.',
                content: `<p>Payment fraud is a growing problem. One time QR codes ensure each transaction is unique and can't be reused, making mobile payments safer for everyone.</p>`
            },
            {
                title: 'What Makes a QR Code Truly Secure?',
                img: 'images/blog14.jpg',
                author: 'OneScan Team',
                date: '2024-06-25',
                summary: 'A checklist for evaluating the security of any QR code solution you use.',
                content: `<ul><li>One time use</li><li>Backend validation</li><li>Encrypted data</li><li>Transparent destination preview</li></ul><p>OneScan checks all these boxes and more.</p>`
            },
            {
                title: 'The Role of Design in QR Code Security',
                img: 'images/blog15.jpg',
                author: 'OneScan Team',
                date: '2024-06-27',
                summary: 'How thoughtful design and UX can make QR code security accessible to everyone.',
                content: `<p>Security shouldn't come at the cost of usability. OneScan's design makes secure QR codes easy and intuitive, so everyone can stay safe without hassle.</p>`
            }
        ];

        // Only inject cards if the grid is empty, to prevent duplication
        if (blogGrid.children.length === 0) {
            blogPosts.forEach((post, idx) => {
                const card = document.createElement('article');
                card.className = 'blog-card apple-card';
                card.dataset.idx = idx;
                card.innerHTML = `
                    <div class="blog-card-img-wrap"><img src="${post.img}" alt="${post.title}" class="blog-card-img"></div>
                    <div class="blog-card-content">
                        <h2 class="blog-card-title">${post.title.replace('-', ' ')}</h2>
                        <p class="blog-card-summary">${post.summary.replace('-', ' ')}</p>
                        <a href="blog-post.html?id=${idx}" class="blog-readmore" aria-label="Read more about ${post.title.replace('-', ' ')}">Read more <i class="fas fa-arrow-right"></i></a>
                    </div>
                `;
                blogGrid.appendChild(card);
            });
        }

        const blogCards = document.querySelectorAll('.blog-card');
        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('visible');
                    observer.unobserve(entry.target);
                }
            });
        }, { threshold: 0.1 });
        blogCards.forEach(card => observer.observe(card));

        const blogModalImg = blogModal.querySelector('.blog-modal-img');
        const blogModalTitle = blogModal.querySelector('.blog-modal-title');
        const blogModalDesc = blogModal.querySelector('.blog-modal-desc');
        const blogModalClose = blogModal.querySelector('.timeline-modal-close');
        const blogModalBackdrop = blogModal.querySelector('.timeline-modal-backdrop');

        function openBlogModal(idx) {
            const post = blogPosts[idx];
            if (!post) return;
            blogModalImg.src = post.img;
            blogModalImg.alt = post.title;
            blogModalTitle.textContent = post.title.replace('-', ' ');
            // Add author and date above content
            let metaHtml = `<div class='blog-modal-meta' style='margin-bottom:1rem;font-size:1.01rem;color:var(--subtle-text);'><span><i class='fas fa-user'></i> ${post.author}</span> · <span><i class='fas fa-calendar-alt'></i> ${post.date}</span></div>`;
            blogModalDesc.innerHTML = metaHtml + post.content.replace('-', ' ');
            // Add related posts at the bottom
            const related = blogPosts
                .map((p, i) => ({...p, idx: i}))
                .filter(p => p.idx !== idx)
                .sort(() => Math.random() - 0.5)
                .slice(0, 3);
            const relatedHtml = `<div class='related-posts-section' style='margin-top:2.2rem;'><h3>Related Posts</h3><div class='related-posts'>${related.map(r => `
                <a class='related-post-card' href='blog-post.html?id=${r.idx}'>
                    <img src='${r.img}' alt='${r.title}' class='related-post-img'>
                    <div class='related-post-title'>${r.title.replace('-', ' ')}</div>
                    <div class='related-post-summary'>${r.summary.replace('-', ' ')}</div>
                    <div class='related-post-meta'>By ${r.author} · ${r.date}</div>
                </a>
            `).join('')}</div></div>`;
            blogModalDesc.innerHTML += relatedHtml;
            blogModal.style.display = 'flex';
            document.body.style.overflow = 'hidden';
            setTimeout(() => blogModal.classList.add('active'), 10);
        }
    }

}); 